const translations = {
  en: {
    ens:"Society",
end:"Country",
enp:"Environment",
    en1: "Home",
    en2: "About Us",
    en3: "Work",
    en4: "Training",
    en5: "Women's Empowerment",
    en6: "Products",
    en7: "Gallery",
    en8: "Contact",
    en9: "training",
    en10: "products",
    en11: "A hand of humanity",
    en12: "A youth development arm",
    en13: "A nature conservation arm",
    en14: "A hand of self-reliance",
    en15: "A hand for the future",
    en16: "Official Partner",
    en17: "Leaders for social welfare and social development",
    en18: "Agriculture plus industry milk production",
    en19: "Keeping in view the benefits of agriculture as adjunct industry,dairy business and milk production training programs were implemented for the new generation and farmers.",
    en20: "Remedial plan for dumb animals",
    en21: "For the welfare of dumb animals and the benefit of farmers by producing animal feed through natural processes, various schemes of the government and the organization were implemented and worked at that place.",
    en22: "able woman",
    en23: "Protection training programs for women and girls were implemented on a large scale.",
    en24: " Child Development and Child Protection Awareness",
    en25: "Based on UNICEF's Dhavalkranti Samyukt Vidyamandan child protection, folk theater and street theater training workshops were conducted and public awareness was created.",
    en26: "cooler distribution",
    en27: "Coolers were distributed in rural areas through District Rural Development System Project Director.",
    en28: "Role and Responsibilities Training Program of w.d.t , p.i.a and w.c",
    en29: "Educational guidance and educational assistance to the new generation",
    en30: "Some Steps for Religion and Communal Reconciliation",
    en31: "In order to maintain peace and unity in the society, Dainik Sakal Police Commissioner's Office and Near Kranti jointly organized the issue of Jatani Salokha Hi Need of the Time.",
    en32: "Employment generation and various training",
    en33: "Training in spice industry for the youth to find work and development of their families, efforts to create employment through various means and drought relief programs were conducted to stop the losses due to drought.",
    en34: "Various trainings for backward class youths and girls",
    en35: "Various trainings were given to the youths for their development and to make them competent and independent. Such as interior design and decoration training, insurance consultancy, bakery production, mural painting and others",
    en36: "Awareness of outdoor sports",
    en37: "By inculcating interest in sports among rural and urban students. The sports complex was built with the view of producing maximum number of players by emphasizing the importance of sports.",
    en38: "skills training",
    en39: "Various self-employment skill training programs were implemented through Dhavalkranti to enable the youth to come forward and develop.",
    en40: "The district officer gave a letter of appreciation for the work of Dhavalkranti.",
    en41: "Efficient for environmental conservation and future benefit",
    en42: "Hazardous waste disposal",
    en43: "Special steps were taken to eliminate hazardous wastes that are harmful to the environment and create pollution. By collecting hazardous waste from various industrial estates and other areas. It was disposed of properly.",
    en44: "Recycling expired food",
    en45: "Expired food generated in large quantities under waste prevention and pollution prevention can be recycled and used to produce natural fertilizers.",
    en46: "Agricultural texture improvement, soil analysis",
    en47: "Considering that the texture of farm land should always be good so that the crop grows better and increases the yield. Work was done accordingly by implementing various activities.",
    en48: "environmental awareness trip",
    en49: "Considering the importance of water and the need for environmental awareness, watershed course trips were organized.",
    en50: "water conservation training",
    en51: "Considering the importance of water and water storage. Project level training was imparted under Integrated Watershed Management Program under Project Training Organization (PTO).",
    en52: "Watershed Management Programme",
    en53: "Under this program, information about the District Watershed Development System project, implementation mechanism, information about self-help group formation, and self-help group functioning were evaluated.",
    en54: "Founder, Dhavalkranti Aurangabad",
    en55: "Doctor Kishore Udaan",
    en56: "Founder, Dhavalkranti Research and Development Foundation",
    en57: "Dhawalkranti was born from the concept of Dr. Kishore Udaan and was realized.",
    en58: "The entire world was affected by an epidemic like Corona. Corona was increasing day by day. This epidemic also took Aurangabad in its grip and the number of Corona victims was increasing day by day. At this time, Aurangabad Police and Dhavalkranti acted as a shield between Corona and the residents. By working night and day, they have done their work. They have raised awareness from time to time about how to protect themselves against Corona. To Dr. Kishore Udan, dedicated to an extraordinary effort organized to help people affected by the 19 pandemic.",
    en59: "Objectives of Dhavalkranti Research and Development Foundation:",
    en60: "To undertake development oriented programs through people's participation for the economic and social upliftment of the weaker sections of the rural areas. Simultaneously by forming self-help Gana groups at the village level. Through them to implement development programs.",
    en61: "Undertaking Participatory Research and Development Program for Dairy Business Development.",
    en62: "Undertaking capacity building training and action program related to complementary cottage / small scale business related to dairying through women self help groups.",
    en63: "Organizing seminars related to agriculture and ancillary business development of farmers in rural areas through agricultural colleges, agricultural universities and undertaking appropriate research work as per the need.",
    en64: "To undertake programs with the help of State Government, Central Government, National and International NGOs to make veterinary clinics and services available to rural farmers.",
    en65: "Formulation and implementation of appropriate public participation policies with a view to increasing milk production.",
    en66: "Implementation of State and Central Government Schemes for creating cold storage, cooler, transportation etc. facilities for milk production.",
    en67: "Development and Implementation of Social Forestry, Nursery E. Constructive Action Programs for Environmental Conservation and Conservation.",
    en68: "Planning of Watershed Development Program including implementation of programs related to soil conservation, water conservation and conservation of other natural resources.",
    en69: "To develop extension programs for the promotion and dissemination of technology in the fields of organic farming, agro-based industries, fisheries, orchard cultivation, animal husbandry, poultry farming, etc. for the upliftment of the rural masses, along with developing research centers and demonstrations.",
    en70: "Setting up Vocational Training Center for self-employment of rural women, youth and dropout boys and girls.",
    en71: "Starting of Public Library and Libraries.",
    en72: "Undertaking programs for primary health care and health education for rural women and children, creating awareness about family planning and family welfare.",
    en73: "Implementing appropriate feeding programs to stop malnutrition among women and children.",
    en74: "To carry out a complete sanitation campaign and make efforts to deodorize the village.",
    en75: "Designing and implementing programs related to non-conventional energy.",
    en76: "SOME MEASURE SCHEME TO MAKE ADOPTED VILLAGES DEVELOPED VILLAGES :",
    en77: "DRDF, Community Policing and Art of Living Digital India Moment have come together to adopt ten villages near Waluj Police Station Aurangabad.",
    en78: "Health Care and Nutrition Program",
    en79: "Promotion of Women's Self-Help Groups",
    en80: "Water Management and River Rejuvenation",
    en81: "Dairy Development",
    en82: "Group Farming",
    en83: "Promotion of Organic Farming",
    en84: "Health Screening Program for Adolescent Girls",
    en85: "Literacy",
    en86: "Village Digital through Cleanliness and Sanitation",
    en87: "Digital Entrepreneurship and Literacy",
    en88: "Mobile Medical Clinics",
    en89: "Skill Training and Placement",
    en90: "De-Addiction Programs and Workshops",
    en91: "Taking Self Defense Programs for Girls and Women",
    en92: "DRDF with community policing installs 2 blinkers in Walaj",
    en93: "premises to prevent road accidents.",
    en94: 'Important meetings were held between the Sarpanch, Deputy Sarpanch and Gram Panchayat members in the selected villages for the concept of "MODEL Village".',
    en95: "Jardgaon Development Programme:",
    en96: "Making developed and developing villages is the main objective of DRDF - Dhavalkranti. Ambitious initiatives and schemes for health, health environment education, literacy and development of residents at village level with the help of Swarajya Gramin Vikas Pratishthan in Jardgaon. Also innovative schemes It has been organized.",
    en97: "Health Care and Nutrition Programs.",
    en98: "Promotion of Women's Self-Help Groups.",
    en99: "Dairy Development and Goat Husbandry.",
    en100: "Health Screening Program for Adolescent Girls.",
    en101:
      "Group Farming: Horticulture from Group Farming to Villages in Ghansawangi and Partur Blocks.",
    en102:
      "Organic Farming: People have developed the best practices in 5 villages and the same practices have been adopted by the villagers themselves in the surrounding villages. 5 Farmer Clubs have been formed in the project area and 11 self-help groups have been established.",
    en103:
      "Water Management: 80 Recharge Wells, Water Conservation and Groundwater Replenishment Program.",
    en104:
      "Increase in Socio-Economic Status through Dairy Development Programme.",
    en105:
      'The project area Jiradgaon was awarded "Nirmal Gram Puraskar" (Clean Village Award) by the President of India.',
    en106:
      "IBN Lokmat makes 30-minute documentary on work and features articles in local newspapers.",
    en107: "Drinking Water Facility :",
    en108:
      "Bangla, Walaj, Aurangabad Dahegaon has a well from ancient times. This well provides a large source of water. Which is very useful for the residents of the surrounding area but the water was contaminated with large amounts of waste in this water, which is dangerous for the health of the residents. For this, D.R.D.F Together with policing cummunity, the water in the ancient well was cleaned and made available to the residents.",
    en109:
      "State's first tribal agricultural training center inaugurated at Don village of Gangapur.",
    en110:
      "In order to create self-reliance among the tribal farmers and to develop their personality among the tribal youth, under the scheme of Self-reliant Tribal Farmers and the powerful Panchayat Raj Institution, the talukas of Soygaon Kannada Sillod Baijapur in the district of the state have been selected for the first tribal agricultural training. The inauguration of the center was completed online on 27th at Dongaon in Gangapur taluka by Tribal Development Minister Arjun Munda and Art of Living inspiration Shri Shri Ravi Shankar. In the training center at Dongaon, 10,000 tribals from 10 Gram Panchayats including Bhils, Pardhis, Lamhas and other castes.In next three years Training will be provided in phases over the years in which organic farming, Goshala and natural farming related businesses will be conducted in a scientific manner. Guidance and certification courses related to organic farming will be conducted from time to time regarding seed conservation and development. For this, ten Yuvacharyas of Art of Living are going to be at the center full time.",
    en111: "Dr Kishore Udaan, Dhawalkranti met Rohit Dada Pawar.",
    en112:
      "Rohit Dada Pawar took special notice and said that if the police and citizens work together in coordination, there can be a big positive change in the society. It is important for everyone to work together for the development of the society and to maintain balance in the society. An epidemic like Corona had disturbed everyone in this epidemic, the police and The coordination of citizens is very useful in defeating epidemics like Corona. Similarly, if coordination between police and citizens can be of great help in completing many social and environmental as well as different developments as soon as possible.",
    en113: "Corona",
    en114:
      "Dhawalkranti Research and Development Foundation and Aurangabad Police together took some decisive steps and formed a cooperative force to help the residents.",
    en115: "Resident Assistance",
    en116: "Ration Kit",
    en117: "Food Pockets",
    en118: "Santoor Soap Distribution",
    en119: "Triple Layer Mask Allocation",
    en120: "Distribution of tablets",
    en121: "Distribution of Bata Shoes",
    en122: "Relocation or Aid",
    en123: "Women employment",
    en124: "employment in Corona",
    en125: "Mohalla Covid Volunteers",
    en126:
      "Mohalla Covid Volunteers group was started from Pundalik Nagar area. During this, examination was done by oximeter thermometer. As many as thirteen groups were formed in Pundalik Nagar area. Mohalla Kovid Volunteers were going door to door and checking the citizens taking proper precautions. So the suspects in this area Pundalik Nagar Police Station Cooperation Police Inspector Sonwane said that the patient will be helped immediately.",
    en127: "Covid 19 Task Force",
    en128:
      "During the Corona period, when the numbers are increasing at a massive rate, 19 Task Covid Volunteers have done a great job. They personally went to each house and tried to maximize the number of affected residents and provide them with immediate treatment. During this period, 20 Radiologist Doctor Sharad Kondekar handed over the plus oximeter to the police administration, according to Divya Marathi.",
    en129: "Women cooperate",
    en130:
      "As employment stopped, Prajakta Bhawar thought about what he could do at home, he came up with the idea of making masks. He gathered all the women in the area and told his idea, but the question was what to do? Masks were the most demanded during the curfew. That's why it was decided to make masks at home.When many women did not have sewing machines, the policing community and Dhavalkranti extended a helping hand.",
    en131: "Women or Employment",
    en132:
      "Through community policing and Dhavalkranti organization, 47 women were given employment in Savera company. Community policing and Dhavalkranti research organization organized an employment fair in Walaj area, hence this concept came forward.",
    en133: "Rehabilitation of Offenders",
    en134:
      "Due to the lockdown and curfew imposed in the country due to corona virus infection, the thieves faced a lot of problems. Some of them even went hungry. It is the intention of Police Commissioner Chiranjeevi Prasad that criminals should be rehabilitated under the Police Community Initiative. Efforts are underway to divert them to employment. This activity was carried out on the order of the senior officer so that their food would not suffer during this period.",
    en135: "Migrants or Aid",
    en136:
      "During the period of Corona, the migrants were stranded at Karma-Bhoomi. They thronged the railway platforms in large numbers to go back to their homes. But they had to stay at the same place as all the facilities were closed and there was no food or basic necessities at that place. Moved ahead and arranged basic needs there.",
    en137: "Community Policing",
    en138:
      "Dhavalkranti Research and Development Foundation and Aurangabad Police have always worked diligently to solve the biggest problems of the residents.",
    en139: "social work",
    en140:
      "Dhawalkranti has always been at the fore for the development of the society and bringing about innovative changes. Dhawalkranti has so far taken many decisive steps and emphasized on the development of the society.",
    en141:
      "Training of Backward Classes from Dr. Kishore Udan's concept and Dhavalkranti",
    en142:
      "By giving training to the backward class youths in various fields. To empower them and they should move towards development by creating their own self-employment. A small effort for this is that Dhavalkranti is giving different trainings to such backward class youths. Under this training, a total of 25 different trainings in brief The information has been given. A small effort is being made by the Dhavalkranti Foundation for the backward class youth to go ahead and become self-reliant.",
    en142_:
      "Considering the importance of education, DRDF has always been taking active and effective steps to develop the new generation and reduce their unemployment rate. Some concrete and decisive steps were taken in coordination with DRDF and Dhavalkranti. Young men and women should develop and create new self-employment. For this, by providing them guidance, education and training in engineering technology. Special efforts were also made to provide employment opportunities to them. Fellows were appointed to guide the students until they found employment after completing their training. Young men and women should develop and create new self-employment. For this, by providing them guidance, education and training in engineering technology. Special efforts were also made to provide employment opportunities to them. Fellows are appointed to guide the students on completion of their training until they find employment.",
    en143:
      "Various Vocational Training Program for Backward Youth / Young Women",
    en144: "Interior Design and Decoration Training.",
    en145: "Mural Painting Training.",
    en146: "Lamasa Art Training.",
    en147: "Jute Bag Making and Bamboo Art Making Training.",
    en148: "Photo Lamination and Frame Training.",
    en149: "Sanitary Napkin Training.",
    en150: "Childcare Training.",
    en151: "Insurance Consultant Training.",
    en152: "Nutritious Diet and Health Training.",
    en153: "Front Office Commission Training.",
    en154: "Travels and Tourism Representative Training.",
    en155: "Online Service Training.",
    en156: "Candle Making Training.",
    en157: "Laundry Training.",
    en158: "Beauty Consultant Training.",
    en159: "Industrial Security Guard Training.",
    en160: "Training in Making Bakery Products.",
    en161: "Soft Skills for Baseline Staff Training.",
    en162: "Assistant Fire Operator Training.",
    en163: "Quality Inspector Training.",
    en164: "Refrigerator / Air Conditioning Mechanic Training.",
    en165: "Training in making paper bags and paper bags.",
    en166: "Training in Basic Computer Education.",
    en167: "Internet Training.",
    en168:
      "Training in making cloth bags and masks and different types of bags.",
    en169: "Interior Design/Decoration",
    en170: "Mural Painting",
    en171: "Lamasa Art",
    en172: "Jute Bag Making",
    en173: "Photo/Frame Lamination",
    en174: "Sanitary Napkin",
    en175: "Childcare",
    en176: "Insurance Consultant",
    en177: "Nutritional Diet/Health",
    en178: "Front Office Commission",
    en179: "Tourism Representative",
    en180: "Online Service",
    en181: "candle making",
    en182: "Laundry Training",
    en183: "Beauty Consultant Training",
    en184: "Industrial Security Guard",
    en185: "Making Bakery Products",
    en186: "Soft Skill",
    en187: "Assistant Fire Operator",
    en188: "Quality Inspector",
    en189: "Air Conditioning Mechanic",
    en190: "Paper Bags/Paper Bags",
    en191: "Basic Computer Education",
    en192: "Internet Training",
    en193: "Mask Making",
    en194: "Training",
    en195: "All training and information about it",
    en196: "A.No",
    en197: "Subject Name",
    en198: "day",
    en199: "Teaching",
    en199_: "Hours",
    en200: "Interior Design and Decoration Training.",
    en201: "45 days",
    en202: "90 Hours",
    en203: "Mural Painting Training.",
    en204: "15 days",
    en205: "30 hours",
    en206: "Lamasa Art Training.",
    en207: "15 days",
    en208: "30 hours",
    en209: "Jute Bag Making and Bamboo Art Making Training.",
    en210: "30 days",
    en211: "60 Hours",
    en212: "Photo Lamination and Frame Training.",
    en213: "20 Days",
    en214: "40 Hours",
    en215: "Sanitary Napkin Training.",
    en216: "10 days",
    en217: "20 Hours",
    en218: "Child Care Training.",
    en219: "10 days",
    en220: "20 Hours",
    en221: "Insurance Consultant Training.",
    en222: "30 days",
    en223: "60 Hours",
    en224: "Nutritious Diet and Health Training.",
    en225: "30 days",
    en226: "60 Hours",
    en227: "Front Office Commission Training.",
    en228: "45 days",
    en229: "90 Hours",
    en230: "Travels and Tourism Representative Training.",
    en231: "60 Days",
    en232: "120 Hours",
    en233: "Online Service Training.",
    en234: "30 days",
    en235: "60 Hours",
    en236: "Candle Making Candle Making Training.",
    en237: "15 days",
    en238: "30 hours",
    en239: "Laundry Training.",
    en240: "15 days",
    en241: "30 hours",
    en242: "Beauty Consultant Training.",
    en243: "60 Days",
    en244: "120 Hours",
    en245: "Industrial Security Guard Training.",
    en246: "30 days",
    en247: "60 Hours",
    en248: "Training in Making Bakery Products.",
    en249: "15 days",
    en250: "30 hours",
    en251: "Soft Skills for Baseline Staff Training.",
    en252: "30 days",
    en253: "60 Hours",
    en254: "Assistant Fire Operator Training.",
    en255: "30 days",
    en256: "60 Hours",
    en257: "Quality Inspector Training.",
    en258: "30 days",
    en259: "60 Hours",
    en260: "Refrigeration / Air Conditioning Mechanic Training.",
    en261: "30 days",
    en262: "60 Hours",
    en263: "Training in making paper bags and paper bags.",
    en264: "10 days",
    en265: "20 Hours",
    en266: "Training in Basic Computer Education.",
    en267: "30 days",
    en268: "60 Hours",
    en269: "Internet Training.",
    en270: "15 days",
    en271: "30 hours",
    en272: "Cloth bags and mask training.",
    en273: "15 days",
    en274: "30 hours",
    en275: "Technology Training and Employment Opportunities",
    en276:
      "Considering the importance of education. DRDF has always been taking active and effective steps for the development of new generation and reduction of unemployment rate. Some concrete and decision-making steps were taken in coordination with DRDF and Dhavalkranti. Youth and young women should develop and create new self-employment. To provide them with guidance, education and employment opportunities By providing guidance, education and training to them, special efforts were made to provide them with employment opportunities.",
    en277:
      "Under Indo-German tool providing information and guidance and training to 178 students on various technologies. Work is underway to develop them.",
    en278: "78 students are undergoing training under CIPET.",
    en279: "Technology Training",
    en280: "Indo German Tools Training and Information",
    en281: "Certificate Course in Machine Operations",
    en282: "Certificate Course in CNC Turing & Milling",
    en283: "Condensed Course in Tool & Die Making",
    en284: "Certificate Course in CNC Milling",
    en285: "Certificate Course in CNC Turning",
    en286: "Advance Certificate Course in CNC Machining",
    en287: "Advance Certificate Course in Welding Technology",
    en288: "Certificate Course in Machining",
    en289: "Post-Diploma in Tool and Die Manufacturing",
    en290: "Master Certificate Course in CNC Technology",
    en291: "Machine Operator - Injection Moulding",
    en292: "CIPET Training and Information",
    en293: "Maintenance of Machinery - Technician",
    en294: "Maintenance of Machinery - Technician",
    en295: "DRDF and Community Police provide employment.",
    en296:
      "Twenty-nine students were employed in the company. They were given attendance of four hundred and fifty per day.",
    en297:
      "Twenty-one students were employed as trainees on a monthly salary of Rs. 7,000 to 10,000.",
    en298:
      "Ten students were trained and employed as trainees in the field of robotics.",
    en299:
      "Forty students were trained in proper laser welding technology and these technicians were promoted.",
    en300: "For Quality Facilitation and Educational Preparation",
    en301:
      "Understanding the problems of the students at the ground level, they should be able to get quality education and prepare for the curriculum. Along with good and quality education, it is very important to create a learning environment for the children. Therefore, DRDF and Dhavalkranti are creating some facilities for the children at the ground level. .The responsibility for educational development has been fulfilled.",
    en302:
      "Library facility in various areas: Indira Nagar, Shatabdi Nagar, Baijipura, Library facility for Orphanage.",
    en303:
      "Study room facility: Construction of library and study room for children preparing for state services and civil services and orphans in Baijipura.",
    en304:
      "Various Competitions for Comprehension of Students: Essay Writing Competitions Conducted in Various Schools.",
    en305: "Night classes started: Night time training facilitated.",
    en306:
      "Library is provided for students to prepare for their academic courses. Students prepare for major courses like state services and civil services. For that they need library and libraries to create a conducive environment.",
    en307: "Facilitation of Study Centers in Indiranagar, Garkheda, Aurangabad",
    en308:
      "Facilitation of Study Center for Baitul Yatim Trust, Fort Arch, Aurangabad Orphanage",
    en309: "Facilitation of Study Center in Shatabdi Nagar Aurangabad",
    en310:
      "Facilities of Indiranagar Baijipura Noor Gate Aurangabad Study Centre",
    en311:
      "A night training center was started in Sanjay Nagar, near Mukundwadi Police Station, Aurangabad. It was an initiative to increase literacy. All were encouraged for night training and all due responsibilities were carried out.",
    en312:
      "A large library was provided in Baijipura ward for students preparing for competitive exams and police recruitment and also for students preparing in computer subjects. Also 200 to 250 orphans of that area benefited greatly from this library.",
    en313:
      "Many children go down the wrong path at an early age due to lack of proper guidance. So if they are guided, they create in their minds the goal of becoming a good citizen and doing something great for the society.work to change their mind and give them proper guidance. The work was done by Dhavalkranti through various programs.",
    en314:
      "Many children go down the wrong path at an early age due to lack of proper guidance. So if they are guided, they create in their minds the goal of becoming a good citizen and doing something great for the society. work to change their mind and give them proper guidance. The work was done by Dhavalkranti through various programs.",
    en315:
      "Community Policing DRDF organized programs to encourage and guide entrepreneurship. Workshops were conducted for unemployed youth in the city. 48 youths were trained and encouraged for entrepreneurship.",
    en316:
      "Dhawalkranti DRDF and Community Policing coordinate activities for women.",
    en317:
      "Dhawalkranti is always trying in many ways to make women self-reliant and empowered in different ways. Like training women, giving them self-defence training, imparting literacy to uneducated women, implementing various activities for women's health, making women self-reliant by providing employment. For these various activities Dhawalkranti Always implements decision-making steps and remedial plans in collaboration with DRDF and community policing colleagues.",
    en318: "Women Empowerment",
    en319: "Providing Training and Markets for Minor Skills.",
    en320: "Trained 10 women to make cotton wigs.",
    en321: "Cosmetics Training.",
    en322: "Incense Making Training.",
    en323: "LED Lights Manufacturing.",
    en324: "Making Paper Bags.",
    en325: "Training in using a sewing machine.",
    en326: "16 women trained in sewing machine in Shatabdi Nagar.",
    en327:
      "One and a half hundred women in poor areas of Kranti Chowk were trained and provided employment in LED making.",
    en328:
      "Women who lost their jobs due to the plastic ban were trained in how to make paper bags and seven women in Indiranagar and fifteen women in Misarwadi were given employment.",
    en329:
      "Muslim women lost their jobs due to the ban on beep meat. 49 such women were trained to make paper bags. They were given employment. These included women from Moti Karanja and Sillekhan.",
    en330:
      "Women who were trained to make paper bags produced 34,000 paper bags in eighteen days. They sold them to hospitals, restaurants and malls.",
    en331:
      "Working with Harsh and Sanjay Beauty Mall and DRDF in community policing collaboration trained 50 women and girls in cosmetics.",
    en332: "Various Activities and Information:",
    en333:
      "In Shatabdi Nagar, Aurangabad, 16 women were trained how to make incense and later given employment.",
    en334:
      "A total of 150 women in poor areas of Kranti Chowk, Aurangabad were trained on how to make LED lights and They were given employment.",
    en335:
      "200 women from Vadgaon (Kolhati) Aurangabad were given sewing machine training and sewing training. They were given employment.",
    en336:
      "Community Policing with Harsh and Sanjay Beauty Mall and DRDF trained 50 women in cosmetics and made them self-reliant.",
    en337:
      "1550 young women in various colleges and districts were trained on how to protect themselves for women empowerment and self-defence.",
    en338:
      "Many women who lost their jobs due to various reasons were given employment by training them on how to make paper bags.They were given employment",
    en339:
      "Many women lost their jobs due to plastic ban. Seven women in Indiranagar were trained to make paper bags and They were given employment.",
    en340:
      "Women in Mirsawadi lost their jobs due to plastic ban. Fifteen women were trained to make paper bags.",
    en341:
      "Muslim women lost their jobs due to closure of BIF. Some women in Moti Karanja, Aurangabad were trained to make paper bags.",
    en342:
      "Because of the closure of Biff, some women in Seallekhana, Aurangabad were given training in how to make paper bags.",
    en343:
      "Women organized a two-day market in Frozen Mall, Aurangabad to sell home-made cloth bags and other items.",
    en344:
      "Women near Waluj Police Station Area, Aurangabad made a total of thirty-four thousand paper bags in eighteen days and sold them in hospitals, restaurants, malls and other places.",
    en345:
      "Solutions for Expired Food Recycling through Dhavalkranti Foundation.",
    en346:
      "Dhavalkranti Foundation is thinking that by recycling the large amount of expired food which is not useful for human consumption, we can make fertilizer from it which we can use to improve our agriculture and we can also make animal feed from that expired food for different types of domestic cows and buffaloes. Dhawal Kranti came up with the idea of getting in touch with the places and companies that produce expired food and collect all the expired food from them and process it for fertilizer and animal feed.",
    en347: "Manufacture of Manure and Fodder from Outdated Material:",
    en348: "Collecting expired food and making natural fertilizer from it",
    en349:
      "To carry out various activities to improve the texture of agricultural land.",
    en350:
      "Undertaking capacity building training and action program related to complementary cottage/small scale business related to dairying through Women Self Help Groups",
    en351:
      "Organizing seminars related to agriculture and ancillary business development of farmers in rural areas through agricultural college, agricultural university and undertaking appropriate research work as per need.",
    en352:
      "For the welfare of dumb animals by producing animal fodder through natural processes and implementing various schemes of the government and the organization for the welfare of the farmers.",
    en353: "Important Leaves",
    en354: "home",
    en355: "information",
    en356: "Works",
    en356_1: "women empowerment",
    en356_2: "eduction",
    en356_3: "products",
    en357: "photo",
    en358: "For more information",
    en359: "Flat No. 108, Gate No. 228/1, Amrit Aura",
    en359_1: "Dehu-Alandi Road, Moshi",
    en359_2: "Maharashtra - 412 105",
    en360: "Contact: (+91) 8421596912",
    en361: "Dr. Kishore Udan : +(91) 9421421440",
    en362: "Praveen Jadhav: +(91) 7350000369",
    en363: "24/7 at your service",
    en364: "address",
    en10d: "10 days",
    en15d: "15 days",
    en20d: "20 Days",
    en30d: "30 days",
    en45d: "45 days",
    en60d: "60 Days",
    en90d: "90 Days",
    en01: "1",
    en02: "2",
    en03: "3",
    en04: "4",
    en05: "5",
    en06: "6",
    en07: "7",
    en08: "8",
    en09: "9",
    en010: "10",
    en011: "11",
    en012: "12",
    en013: "13",
    en014: "14",
    en015: "15",
    en016: "16",
    en017: "17",
    en018: "18",
    en019: "19",
    en020: "20",
    en021: "21",
    en022: "22",
    en023: "23",
    en024: "24",
    en025: "25",
    eng1:"All Photo",
    eng2:"Corona",
    eng3:"Social work",
    eng4:"Comunity Policing",
    eng5:"More",
  },
  mr: {
    ens:"समाजासाठी",
end:"देशहितासाठी",
enp:"पर्यावरणासाठी",
    en1: "मुख्यपृष्ठ",
    en2: "माहिती",
    en3: "कामे",
    en4: "प्रशिक्षण",
    en5: "महिला सशक्तिकरण",
    en6: "उत्पादने",
    en7: "फोटो",
    en8: "संपर्क",
    en9: "प्रशिक्षण",
    en10: "उत्पादने",
    en11: "एक माणुसकीचा हात",
    en12: "एक तरुणाई विकास चा हात",
    en13: "एक निसर्ग संवर्धन चा हात",
    en14: "एक आत्मनिर्भरते चा हात",
    en15: "एक भविष्यासाठी चा हात",
    en16: "अधिकृत पार्टनर",
    en17: "समाज हितासाठी आणि समाज विकासासाठी अग्रेसर",
    en18: "शेती जोड उद्योग दूध निर्मिती",
    en19: "शेतीला जोड उद्योग आणि त्यातील फायदा लक्षात घेता नवीन पिढी व शेतकरी बांधव यांना दुग्ध व्यवसाय व दुग्धोत्पादन प्रशिक्षण कार्यक्रम राबविण्यात आले.",
    en20: "मुक्या जनावरांसाठी उपाय योजना",
    en21: "पशुखाद्यांची नैसर्गिक प्रक्रियेतून निर्मिती करून मुक्या जनावरांच्या कल्याणासाठी व शेतकऱ्यांच्या हितासाठी शासनाच्या व संस्थेच्या विविध योजनांची अंमलबजावणी करून त्या जागोजागी कार्य करण्यात आली.",
    en22: "सक्षम महिला",
    en23: "महिला मुलींना संरक्षणाची प्रशिक्षण कार्यक्रम मोठ्या प्रमाणात राबविण्यात आले",
    en24: "बाल विकास व बाल संरक्षण जनजागृती",
    en25: "युनिसेफ च्या धवलक्रांती संयुक्त विद्यामंदन बाल संरक्षणावर आधारित लोकनाट्य व पथनाट्य प्रशिक्षण कार्यशाळा राबवण्यात आले आणि जनजागृती करण्यात आली.",
    en26: "कुलर वाटप",
    en27: "जिल्हा ग्रामीण विकास यंत्रणा प्रकल्प संचालक माध्यमातून ग्रामीण भागांमध्ये कुलर वाटप करण्यात आले.",
    en28: "w.d.t , p.i.a आणि w.c यांच्या भूमिका आणि जबाबदारी प्रशिक्षण कार्यक्रम",
    en29: "नवीन पिढीला शैक्षणिक मार्गदर्शन व शैक्षणिक मदत",
    en30: "धर्मवाद व जातीय सलोखा साठी काही पावले",
    en31: "समाजामध्ये शांती आणि एकी कायम राहावी यासाठी दैनिक सकाळ पोलीस आयुक्त कार्यालय व जवळ क्रांती यांच्या संयुक्त विद्यमानाने जातीय सलोखा ही काळाची गरज या क्रमांकाच्या आयोजन करण्यात आले",
    en32: "रोजगार निर्मिती आणि विविध प्रशिक्षण",
    en33: "युवकांना काम भेटावे आणि त्यांच्या परिवाराच्या विकासासाठी मसाला उद्योग प्रशिक्षण, विविध मार्गातून रोजगारांची निर्मिती करण्याचा प्रयत्न व दुष्काळामुळे होणारे नुकसान थांबवण्यासाठी दुष्काळ निवारण कार्यक्रम घेण्यात आले.",
    en34: "मागासवर्गीय युवक - युवतींना विविध प्रशिक्षण",
    en35: "युवक - युवतींच्या विकासासाठी आणि त्यांनी सक्षम व आत्मनिर्भर बनावे.यासाठी त्यांना विविध प्रशिक्षण देण्यात आले. जसे की इंटरियर डिझाईन व डेकोरेशन प्रशिक्षण, विमा सल्लागार, बेकरी उत्पादन ,म्युरल पेंटिंग आणि इतर",
    en36: "मैदानी खेळांविषयी जागरूकता",
    en37: "ग्रामीण व शहरी भागातील विद्यार्थ्यांची खेळाची आवड निर्माण करून. खेळांचे महत्त्व पटवून जास्तीत जास्त प्रमाणात खेळाडू तयार करण्याच्या दृष्टिकोनातून क्रीडा संकुलन उभारण्यात आले.",
    en38: "कौशल्य प्रशिक्षण",
    en39: "तरुणांनी पुढे येऊन सक्षम व विकसित व्हावे यासाठी स्वयंरोजगार कौशल्य प्रशिक्षणाचे विविध कार्यक्रम धवलक्रांतीच्या माध्यमातून राबविण्यात आले.",
    en40: "धवलक्रांती च्या कामाबद्दल जिल्हा अधिकारी यांनी प्रशिस्तीपत्र दिले.",
    en41: "पर्यावरण संवर्धन आणि भविष्य हितासाठी कार्यक्षम",
    en42: "घातक कचऱ्याची विल्हेवाट",
    en43: "पर्यावरणाला हानीकारक व प्रदूषण निर्मिती करणारा घातक कचरा निवारण यासाठी विशेष पावली उचलण्यात आली. विविध औद्योगिक वसाहती व इतर भागातील घातक कचरा संकलन करून. त्याची योग्य ती विल्हेवाट करण्यात आली.",
    en44: "कालबाह्य खाण्याचा पुनःवापर",
    en45: "कचरा निवारण व प्रदूषण निवारण अंतर्गत मोठ्या प्रमाणात निर्माण होणारे कालबाह्य अन्न हे पुन्हा वापर करून त्याचा नैसर्गिक खत निर्मितीसाठी उपयोग करता येऊ शकतो .हे लक्षात घेता.कालबाह्य खाण्याचे संकलन करून नैसर्गिक खतांची निर्मिती करण्यात आली.",
    en46: "शेतीचा पोत सुधारणा भूमी अंकलन",
    en47: "शेत जमिनीचा पोत हा नेहमी चांगला असावा त्यामुळे पिकाची वाढ चांगली होते आणि उत्पादनामध्ये वाढ होते हे लक्षात घेत. विविध उपक्रम राबवून त्या अनुषंगाने काम करण्यात आली.",
    en48: "पर्यावरण जागृतीसाठी सहल",
    en49: "पाण्याचे महत्व आणि पर्यावरण जागृती गरज लक्षात घेता पाणलोट अभ्यासक्रम सहलीचे आयोजन करण्यात आले.",
    en50: "जलसंधारण प्रशिक्षण",
    en51: "पाण्याची महत्त्व व पाण्याचासाठा याचा विचार करत. प्रकल्प प्रशिक्षण संस्था अंतर्गत (पी.टी.ओ) एकात्मिक पाणलोट व्यवस्थापन कार्यक्रमांतर्गत प्रकल्पस्तरावरील प्रशिक्षण देण्यात आले.",
    en52: "पाणलोट व्यवस्थापन कार्यक्रम",
    en53: "या कार्यक्रमांतर्गत जिल्हा पाणलोट विकास यंत्रणा प्रकल्प, कार्यान्वयन यंत्रणा, बचत गट बांधणी बाबत माहिती बचत गट कार्यपद्धती याबद्दल माहिती आणि मूल्यमापन करण्यात आले.",
    en54: "     <h5>संस्थापक, धवलक्रांती औरंगाबाद</h5>",
    en55: "डॉक्टर किशोर उडान",
    en56: "संस्थापक, धवलक्रांती रिसर्च अँड डेव्हलपमेंट फाउंडेशन",
    en57: "डॉक्टर किशोर उडान यांच्या संकल्पनेतून धवलक्रांतीचा जन्म झाला आणि ती साकारण्यात आली.",
    en58: "संपूर्ण जगाला करोंना सारख्या महामारीने विळखा घातला होता. दिवसेन दिवस करोना हा वाढत चाला होता. ह्या महामारीने औरगाबाद ला पण आपल्या विळख्यात घेतल आणि दिवसेन दिवस करोना बादितांची संख्या वाढत चाली होती. ह्या वेळी औरंगाबाद पोलिस आणि धवलक्रांती ही करोना आणि रहिवासी च्या मध्ये ढाल म्हणून उभी राहिली. रात्र आणि दिवस काम करून त्यांनी त्यांची कामगिरी पार पडली . करोना पासून संरक्षण कसे करावे याचे वेळो वेळी जागो जागो जनजागृती करून सर्वाना मनोबल दिले.करोना शी लढा देण्यासाठी धवलक्रांती रिसर्च अँड डेव्हलपमेंट फाउंडेशन पुढे सेरसावली आणि करोना शी दोनह हात केले. कोविड -१९ साथीच्या आजाराने बाधित लोकांना मदत करण्यासाठी आयोजित केलेला एक असाधारण प्रयत्न समर्पित डॉक्टर किशोर उडान यांना.",
    en59: "धवलक्रांती रिसर्च व डेव्हलपमेंट फाऊंडेशन संस्थेचे उद्देश :",
    en60: "ग्रामीण भागातील दुर्बल घटकांच्या आर्थिक आणि सामाजिक उन्नतीसाठी लोकसहभागातून विकासभिमुख कार्यक्रम हाती घेणे. त्याचबरोबर गाव पातळीवर स्वयं-सहाय्यक गण ग्रुप तयार करून. त्यांच्या माध्यमातून विकास कार्यक्रमाचे अंमलबजावणी करणे.",
    en61: "दुग्ध व्यवसाय विकासाच्या संबंधी सहभागीय संशोधन व विकास कार्यक्रम हाती घेणे.",
    en62: "महिला स्वयं-सहाय्यता गटामार्फत दुग्ध व्यवसायाच्या अनुषंगाने पूरक कुटीर / लघुउद्योग व्यवसाय संबंधी क्षमता बांधणी प्रशिक्षण व कृती कार्यक्रम हाती घेणे.",
    en63: "कृषी महाविद्यालय, कृषी विश्व-विद्यालयामार्फत नाविन्यपूर्ण व ग्रामीण भागातील शेतकऱ्यांची शेती व शेतीपूरक व्यवसाय विकास संबंधित चर्चासत्र आयोजन करणे गरजेनुसार योग्य असे संशोधन कार्य हाती घेणे.",
    en64: "पशुवैद्यकीय दवाखाना व सेवा ग्रामीण शेतकऱ्यांना उपलब्ध व्हावी यासाठी राज्यशासन, केंद्रशासन, राष्ट्रीय व आंतरराष्ट्रीय स्वयंसेवी संस्था यांच्या मदतीने कार्यक्रम हाती घेणे.",
    en65: "दुग्धउत्पादन वाढविण्याच्या दृष्टिकोनातून योग्य असे लोकसहभागातून तयार करणे व त्याची अंमलबजावणी करणे.",
    en66: "दुग्ध उत्पादनासाठी शीतगृह, कुलर, वाहतूक इत्यादी सुविधा निर्माण करण्यासाठी राज्य व केंद्र शासनाच्या योजनांची अंमलबजावणी करणे.",
    en67: "पर्यावरण संवर्धन व संरक्षणासाठी सामाजिक वनीकरणे, रोपवाटिका ई .रचनात्मक कृती कार्यक्रम तयार करणे व त्यांची अंमलबजावणी करणे.",
    en68: "पाणलोटक्षेत्र विकास कार्यक्रमाची आखणी करणे त्यात प्रामुख्याने मृदसंधारण, जलसंधारण आणि इतर नैसर्गिक साधन संपत्तीची जपणूक संबंधी कार्यक्रम राबवणे.",
    en69: "ग्रामीण जनतेच्या उन्नतीसाठी सेंद्रियशेती, कृषी आधारित उद्योग, मत्स्य व्यवसाय, फळबाग लागवड पशु संवर्धन कुक्कुटपालन इ. संदर्भात तंत्रज्ञानाच्या प्रचार व प्रसारासाठी विस्तार कार्यक्रम तयार करणे, त्याच बरोबर संशोधन केंद्र आणि प्रात्यक्षिके विकसित करणे.",
    en70: "ग्रामीण महिला, युवक व अर्धवट शिक्षण सोडलेले मुले व मुली यांना स्वयंरोजगार निर्मितीसाठी व्यवसाय प्रशिक्षण केंद्र सुरू करणे.",
    en71: "सार्वजनिक ग्रंथालय व वाचनालय सुरू करणे.",
    en72: "ग्रामीण महिला व बालकांसाठी प्राथमिक आरोग्य सेवा व आरोग्य शिक्षणाच्या संदर्भात कार्यक्रम हाती घेणे, कुटुंब नियोजन व कुटुंब कल्यान या संबंधी जनजागृती करणे.",
    en73: "महिला व बालकांमधील कुपोषण थांबविण्यासाठी योग्य ते आहार कार्यक्रम राबविणे.",
    en74: "संपूर्ण स्वच्छता अभियान राबवणे व गाव दुर्गंधीमुक्ती करण्यासाठी प्रयत्न करणे.",
    en75: "गैर पारंपारिक ऊर्जा संबंधित कार्यक्रम तयार करणे व राबविणे.",
    en76: "दत्तक गावे विकसित गाव बनवण्यासाठी काही उपाय योजना :",
    en77: "वाळूज पोलीस स्टेशन औरंगाबाद शेजारी डी.आर.डी.एफ, कम्युनिटी पोलीसिंग आणि आर्ट ऑफ लिविंग डिजिटल इंडिया मोमेंट यांनी एकत्र येऊन दहा गावे दत्तक घेतले आहे.",
    en78: "आरोग्य सेवा आणि पोषण कार्यक्रम",
    en79: "महिला बचत गटांना प्रोत्साहन",
    en80: "जल व्यवस्थापन आणि नदी कायाकल्प",
    en81: "दुग्धव्यवसाय विकास",
    en82: "गट शेती",
    en83: "ऑरगॅनिकचा शेती प्रचार",
    en84: "किशोरवयीन मुलींचे आरोग्य तपासणी कार्यक्रम",
    en85: "साक्षरता",
    en86: "स्वच्छता आणि स्वच्छताच्या माध्यमातून गाव डिजिटल",
    en87: "डिजिटल उद्योजक आणि साक्षरता",
    en88: "मोबाइल वैद्यकीय दवाखाने",
    en89: "कौशल्य प्रशिक्षण आणि प्लेसमेंट",
    en90: "व्यसनमुक्ती कार्यक्रम आणि कार्यशाळा",
    en91: "मुली आणि महिलांसाठी स्वसंरक्षण कार्यक्रम घेणे",
    en92: "कम्युनिटी पोलिसिंगसह DRDF ने रस्त्यावर होणारे अपघात टाळण्यासाठी वाळूज",
    en93: "परिसरात २ ब्लिंकर बसवले.",
    en94: "विकसित गाव (MODEL Village) या संकल्पनेसाठी निवडलेल्या गावांमध्ये महत्त्वाच्या मीटिंग सरपंच,डेप्युटी सरपंच आणि ग्रामपंचायत सभासद यांच्यामध्ये घेण्यात आले.",
    en95: "जरडगाव विकसित कार्यक्रम:",
    en96: "विकसित आणि विकसनशील गावे बनवणे हा डी.आर.डी.एफ - धवलक्रांती यांचा प्रमुख उद्देश आहे. जरडगाव मध्ये स्वराज्य ग्रामीण विकास प्रतिष्ठान यांच्या सहाय्याने गाव पातळीवर स्वास्थ, आरोग्य पर्यावरण शिक्षण, साक्षरता आणि रहिवाशांचा विकास यासाठी महत्त्वआकांक्षी उपक्रम व योजना. तसेच नवनवीन योजनांचे आयोजन ही करण्यात आले आहे.",
    en97: "आरोग्य सेवा आणि पोषण कार्यक्रम.",
    en98: "महिला बचत गटांना प्रोत्साहन.",
    en99: "दुग्धव्यवसाय विकास आणि शेळीपालन.",
    en100: "किशोरवयीन मुलींचे आरोग्य तपासणी कार्यक्रम.",
    en101: "गट शेती: घनसावंगी आणि परतूर ब्लॉकमधील गावे गट शेतीपासून फलोत्पादन.",
    en102:
      "सेंद्रिय शेती: लोकांनी ५ गावांमध्ये सर्वोत्तम पद्धती विकसित केल्या आहेत आणि आजूबाजूच्या गावामध्ये गावकऱ्याकडून स्वतःहून त्या पद्धतीचा वापर करण्यात आला.प्रकल्प क्षेत्रात ५ शेतकरी क्लब निर्माण करण्यात आले आणि ११ बचत गटांची स्थापना करण्यात आली.",
    en103:
      "पाणी व्यवस्थापन : ८० पुनर्भरण विहिरी, जलसंधारण आणि भूजल पातळीत वाढ कार्यक्रम.",
    en104: "दुग्धविकास कार्यक्रमामुळे सामाजिक-आर्थिक स्थितीत वाढ.",
    en105:
      'भारताच्या राष्ट्रपतींद्वारे प्रकल्प क्षेत्र जिरडगावला "निर्मल ग्राम पुरस्कार" (स्वच्छ गाव पुरस्कार) देण्यात आला .',
    en106:
      "आय.बी.एन लोकमतने ३० मिनीटचा कामावर माहितीपट बनवला आणि स्थानिक वर्तमानपत्रांमध्ये वैशिष्ट्ये वरती लेख.",
    en107: "पिण्याच्या पाण्याची सुविधा :",
    en108:
      "बांगला, वाळूज, औरंगाबाद दहेगावमध्ये प्राचीन काळापासून विहीर आहे. या विहिरीमध्ये पाण्याचा मोठा स्त्रोत उपलब्ध आहे. जो आजूबाजूच्या रहिवाशांसाठी खूप उपयुक्त आहे परंतु या पाण्यामध्ये मोठ्या प्रमाणात कचरा टाकून ते पाणी दूषित करण्यात आले होते असे पाणी रहिवाशांच्या आरोग्यासाठी धोकादायक आहे. यासाठी डी. आर. डी. एफ आणि कम्युनिटी पोलीसिंग एकत्र येऊन. प्राचीनकालीन विहिरीमधील पाण्याची स्वच्छता करून ते पाणी पिण्यायोग्य आणि स्वच्छ करण्यात आले आणि ते पाणी रहिवाशांसाठी उपलब्ध करून देण्यात आले. या स्वच्छ पाण्याचा उपयोग तेथील दीड हजार रहिवाशी करत आहेत.",
    en109:
      "राज्यातील पहिल्या आदिवासी कृषी प्रशिक्षण केंद्रा चे  गंगापूरच्या डोण गावात झाले उद्घाटन. ",
    en110:
      "आदिवासी शेतकऱ्यांना आत्मनिर्भर करण्यासाठी आदिवासी युवकांमध्ये जनजागृती व त्यांच्या व्यक्तिमत्व विकासासाठी आत्मनिर्भर ट्रायबल फार्मर्स आणि ताकदवान पंचायत राज संस्था या योजना अंतर्गत केंद्रीय आदिवासी मंत्रालय व आर्ट ऑफ लिविंग च्या संयुक्त विद्यमानाने राज्यातील जिल्ह्यातील सोयगाव कन्नड सिल्लोड बैजापूर या तालुक्यांची निवड करण्यात आली असून यासाठीच्या पहिल्या आदिवासी कृषी प्रशिक्षण केंद्राचे उद्घाटन गंगापूर तालुक्यातील डोणगाव येथे आदिवासी विकास मंत्री अर्जुन मुंडा व आर्ट ऑफ लिविंग च्या प्रेरणे श्री श्री रविशंकर यांच्या हस्ते ऑनलाईन द्वारे दिनांक २७ रोजी संपन्न झाले. डोणगाव येथील प्रशिक्षण केंद्रामध्ये दहा ग्रामपंचायतीमधील दहा हजारा आदिवासीना ज्यामध्ये भिल्ल, पारधी, लम्हांसह इतर जातीतील. पुढील तीन वर्षांमध्ये टप्प्याटप्प्याने प्रशिक्षण देण्यात येणार आहे त्यामध्ये ऑरगॅनिक फार्मिंग, गोशाळा व नैसर्गिक शेतीशी संबंधित व्यवसाय शास्त्रशुद्ध पद्धतीने करणे बियाण्यांचे संवर्धन व विकास यासंदर्भात वेळोवेळी मार्गदर्शन व जैविक शेती संबंधित प्रमाणपत्र अभ्यासक्रम राबविण्यात येणार आहे आदिवासींनी निर्माण केलेल्या कृषी मालाला बाजारपेठ मिळवून त्यांना आत्मनिर्भर करण्यात येणार असल्याचे यावी सांगण्यात आली यासाठी आर्ट ऑफ लिविंग च्या दहा युवाचार्य पूर्ण वेळ केंद्रावर असणार आहे.",
    en111:
      "डॉक्टर किशोर उडान, धवलक्रांती यांनी घेतली रोहित दादा पवार यांची भेट.",
    en112:
      "रोहित दादा पवारांनी खास दखल घेत सांगितले की पोलिसांनी व नागरिक यांनी समन्वय एकत्र काम केले तर समाजात मोठा सकारात्मक बदल होऊ शकतो. समाज विकासासाठी आणि समाजामध्ये समतोल राखण्यासाठी सर्वांनीच बहूबाजूने प्रयत्न करणे हे महत्त्वाचे आहे. करोना सारख्या महामारीने सर्वांना त्रासवून सोडले होते या महामारीमध्ये पोलीस आणि नागरिक यांच्या समन्वयाने करोनासारख्या महामारीला हरवण्यासाठी खूप उपयोग झाला. असेच जर पोलीस आणि नागरिक यांच्यामध्ये समन्वय साधत अनेक सामाजिक आणि पर्यावरण तसेच तसेच वेगवेगळे विकास लवकरात लवकर पूर्ण करण्यासाठी मोठी मदत होऊ शकते.",
    en113: "करोना",
    en114:
      "धवलक्रांती रिसर्च व डेव्हलपमेंट फाऊंडेशन आणि औरंगाबाद पोलिस यांनी मिळून काही निर्णयात्मक पावले उचली आणि रहिवासीच्या मदतीसाठी सहकारी दल निर्माण केले.",
    en115: "रहिवासीना मदत",
    en116: "रेशन किट",
    en117: "फूड पॉकेट्स",
    en118: "संतूर साबण वाटप",
    en119: "ट्रिपल लेयर मास्क वाटप",
    en120: "टॅब्लेट चे वाटप",
    en121: "बाटा शूज चे वाटप",
    en122: "स्थळांतरिता ना मदत",
    en123: "महिला ना रोजगार दिले",
    en124: "महिला ना करोनात रोजगार दिले",
    en125: "मोहल्ला कोविड वॉलंटियर्स",
    en126:
      "मोहल्ला कोविड वॉलंटियर्स ग्रुपची सुरुवात पुंडलिक नगर भागातून करण्यात आली. याच दरम्यान ऑक्सिमीटर थर्मामीटरद्वारे तपासणी करण्यात आली. पुंडलिक नगर परिसरात तब्बल तेरा ग्रुप तयार करण्यात आले होते. मोहल्ला कोविड वॉलंटियर्स घरोघरी जाऊन आणि योग्य ती खबरदारी घेऊन नागरिकांची तपासणी करत होते. त्यामुळे या भागातील संशयित रुग्ण तात्काळ समोर येण्यास मदत होणार असल्याचे पुंडलिक नगर पोलीस ठाणे सहकार्य पोलीस निरीक्षकांच्या सोनवणे यांनी सांगितले.",
    en127: "कोवीड १९ टास्क फोर्स",
    en128:
      "कोरोना कालावधीमध्ये मोठ्या प्रमाणामध्ये संख्या वाढत असताना अशा कालावधीमध्ये १९ टास्क कोविड वॉलंटियर्स यांनी खूप मोठी कामगिरी बजावली त्यांनी स्वतः प्रत्येकाच्या घरी जाऊन योग्य ती काळजी घेऊन जास्तीत जास्त करून बाधित रहिवासींना शोधून काढून त्यांना तात्काळ उपचार द्याता यावेत यासाठी प्रयत्न केले. याच कालावधीमध्ये ऑक्सिजन पातळी मोजण्यासाठी २० प्लस ऑक्सिमीटर ही भेट दिव्य मराठीच्या वृत्तानुसार रेडिओलॉजिस्ट डॉक्टर शरद कोंडेकर यांनी पोलीस प्रशासनाकडे सोपवले.",
    en129: "महिला ना सहकार्य",
    en130:
      "रोजगार बंद झाल्यामुळे प्राजक्ता भवर यांनी घरबसल्या काय करता येईल का याचा विचार केला, मास्क बनवू ही कल्पना त्यांना सुचली.त्यांनी परिसरातील सर्व महिलांना जमवुण त्यांची कल्पना सांगितली पण प्रश्न होता करायचे काय? मग संचारबंदीत सर्वात जास्त मागणी आली मास्कला. यासाठीच घरीच मास्क बनवायचे ठरले पण खरेदी करणार कोण संचार बंदीत कापड कुठून उपलब्ध होईल. बऱ्याच महिलांकडे शिलाई मशीन नव्हती अशा परस्थितीत पोलीसिंग कॉमुनिटी आणि धवलक्रांती ने मदतीचा हात पुढे केला.",
    en131: "महिला ना रोजगार",
    en132:
      "कम्युनिटी पोलीससिंग आणि धवलक्रांती संस्थेच्या माध्यमातून ४७ महिलांना सवेरा कंपनीमध्ये रोजगार देण्यात आला. कम्युनिटी पोलीसिंग व धवलक्रांती रिसर्च संशोधन संस्थेतर्फे वाळूज परिसरात रोजगार मेळावा घेण्यात आला होता त्यामुळे ही संकल्पना पुढे आली.",
    en133: "गुन्हेगारांचे पुनर्वसन",
    en134:
      "करोंना विषाणू संसर्गामध्ये देशात लॉकडाऊन आणि संचारबंदी लागू असल्यामुळे चोरट्यांची मोठी अडचणी निर्माण झाली होती. काहींवर तर उपासमारीची वेळ आली होती. पोलीस कम्युनिटी उपक्रमांतर्गत गुन्हेगाराचे पुनर्वसन झाले पाहिजे हा पोलीस आयुक्त चिरंजीवी प्रसाद यांचा हेतू आहे. लॉकडाऊनच्या काळात अशा सगळ्या गुन्हेगारांची समुपदेशन करून त्यांना गुन्हेगारी कडून रोजगाराकडे वळवण्याचे प्रयत्न सुरू आहेत. या काळात त्यांच्या जेवणाच्या हाल होऊ नये म्हणून वरिष्ट अधिकारी च्या आदेशाने हा उपक्रम पार पाडण्यात आला.",
    en135: "स्थलांतरित ना मदत",
    en136:
      "कोरोंनाच्या कालावधीमध्ये परप्रांतीय हे कर्म-भूमीच्या जागेवरच अडकून पडले होते. त्यांनी आपल्या घरी परत जाण्यासाठी रेल्वे प्लॅटफॉर्म वर मोठ्या प्रमाणात गर्दी केली होती. परंतु सर्व सोयी बंद असल्यामुळे त्यांना त्याच जागेवरती राहावे लागत होते आणि त्या जागेवरती कोणतेही खाण्याची किंवा मूलभूत गरजांची सोय नव्हती अशावेळी धवलक्रांती पुढे सरसावले आणि तिथे मूलभूत गरजांची व्यवस्था करून दिली.",
    en137: "कम्युनिटी पोलीसिंग",
    en138:
      "धवलक्रांती रिसर्च व डेव्हलपमेंट फाऊंडेशन आणि औरंगाबाद पोलिस यांच्या एकजुटीने रहिवाशांचे मोठ्यात मोठे प्रश्न सोडवण्यासाठी नेहमी तत्पर कार्य करत राहिले.",
    en139: "समाजकार्य",
    en140:
      "समाजाच्या विकासासाठी आणि नव-नवीन बदल घडवून आणण्यासाठी नेहमी धवलक्रांती अग्रेसर राहिली आहे. धवलक्रांतीने आतापर्यंत खूप निर्णयात्मक पावले उचलून समाज विकासावर भर दिला आहे.",
    en141:
      "डॉक्टर किशोर उडान यांच्या संकल्पनेतून आणि धवलक्रांती च्या बरोबर मागासवर्गीयांना प्रशिक्षण",
    en142:
      "मागासवर्गीय युवक-युवतींना विविध क्षेत्रातले प्रशिक्षण देऊन. त्यांना सक्षम बनवणे आणि आणि त्यांनी स्वतःची स्वयंरोजगार निर्मिती करून विकासाकडे वाटचाल करावी. यासाठी एक छोटासा प्रयत्न म्हणजे धवलक्रांती कडून अशा मागासवर्गीय युवक-युवतींना वेगवेगळे प्रशिक्षण देण्यात येत आहे. या प्रशिक्षणा अंतर्गत एकूण २५ वेगवेगळ्या प्रशिक्षणाची थोडक्यात माहिती देण्यात आली आहे.मागासवर्गीय युवक-युवतीने पुढे जावून सक्षम आणि आत्मनिर्भर बनावे. त्यांच्या भविष्याच्या वाटचालीसाठी एक छोटासा हा प्रयत्न धवलक्रांती फाउंडेशन तर्फे करण्यात येत आहे.",
    en142_:
      "शिक्षणाचे महत्त्व लक्षात घेता नवीन पीढीच्या विकासासाठी आणि त्यांच्या बेरोजगारीचा टक्का कमी करण्यासाठी DRDF ही नेहमी सक्रिय आणि प्रभावशाली पावले उचलत आली आहे. DRDF आणि धवलक्रांती यांच्या समन्वयाने काही ठोस आणि निर्णयात्मक पावले उचलण्यात आली. युवकांनी व युवतीने नवीन स्वयंरोजगार विकसित आणि निर्माण करावे. यासाठी त्यांना अभियांत्रिक तंत्रज्ञानाविषयी मार्गदर्शन, शिक्षण व प्रशिक्षण उपलब्ध करून. त्यांना रोजगाराची संधी उपलब्ध व्हावी.यासाठी सुद्धा विशेष प्रयत्न करण्यात आले. विद्यार्थ्यांचे प्रशिक्षण पूर्ण झाल्यावर त्यांना रोजगार मिळेपर्यंत चे मार्गदर्शन पुरवण्यासाठी सहकारी नेमण्यात आले. युवकांनी व युवतीने नवीन स्वयंरोजगार विकसित आणि निर्माण करावे. यासाठी त्यांना अभियांत्रिक तंत्रज्ञानाविषयी मार्गदर्शन, शिक्षण व प्रशिक्षण उपलब्ध करून. त्यांना रोजगाराची संधी उपलब्ध व्हावी.यासाठी सुद्धा विशेष प्रयत्न करण्यात आले. विद्यार्थ्यांचे प्रशिक्षण पूर्ण झाल्यावर त्यांना रोजगार मिळेपर्यंत चे मार्गदर्शन पुरवण्यासाठी सहकारी नेमण्यात आले.",
    en143: "मागस्वर्गीय युवकांना / युवतींना विविध व्यवसाय प्रशिक्षण कार्यक्रम",
    en144: "इंटेरियर डिझाईन व डेकोरेशन प्रशिक्षण.",
    en145: "म्युरल पेंटिंग प्रशिक्षण.",
    en146: "लमासा आर्ट प्रशिक्षण.",
    en147: "ज्युट बॅग मेकिंग व बांबू आर्ट मेकिंग प्रशिक्षण.",
    en148: "फोटो लॅमिनेशन व फ्रेम प्रशिक्षण.",
    en149: "सॅनिटरी नॅपकिन प्रशिक्षण.",
    en150: "बालसंगोपन प्रशिक्षण.",
    en151: "विमा सल्लागार प्रशिक्षण.",
    en152: "पोषक आहार व आरोग्य प्रशिक्षण.",
    en153: "फ्रंट ऑफिस कमिशन प्रशिक्षण.",
    en154: "ट्रॅव्हल्स आणि टुरिझम प्रतिनिधी प्रशिक्षण.",
    en155: "ऑनलाईन सर्विस प्रशिक्षण.",
    en156: "मेणबत्ती बनवणे (कॅण्डल मेकिंग) प्रशिक्षण.",
    en157: "लॉन्ड्री प्रशिक्षण.",
    en158: "सौंदर्य सल्लागार प्रशिक्षण.",
    en159: "औद्योगिक सुरक्षा रक्षक प्रशिक्षण.",
    en160: "बेकरी उत्पादने बनवणे प्रशिक्षण.",
    en161: "सॉफ्ट स्कील फॉर बेसलाइन स्टाफ प्रशिक्षण.",
    en162: "सहाय्यक फायर ऑपरेटर प्रशिक्षण.",
    en163: "गुणवत्ता निरीक्षक प्रशिक्षण.",
    en164: "रेफ्रीजरेटर / एअर कंडिशनिंग मेकॅनिक प्रशिक्षण.",
    en165: "कागदी पिशव्या व कागदी पाकिटे तयार करणे प्रशिक्षण.",
    en166: "मूलभूत संगणक शिक्षणनाचे प्रशिक्षण.",
    en167: "इंटरनेट प्रशिक्षण.",
    en168:
      "कापडी पिशव्या व मास्क व विविध प्रकारच्या बॅग तयार करणे याचे प्रशिक्षण.",
    en169: "इंटेरियर डिझाईन/डेकोरेशन",
    en170: "म्युरल पेंटिंग",
    en171: "लमासा आर्ट",
    en172: "ज्युट बॅग/बांबू आर्ट मेकिंग",
    en173: "फोटो/फ्रेम लॅमिनेशन",
    en174: "सॅनिटरी नॅपकिन",
    en175: "बालसंगोपन",
    en176: "विमा सल्लागार",
    en177: "पोषक आहार/आरोग्य",
    en178: "फ्रंट ऑफिस कमिशन",
    en179: "ट्रॅव्हल्स/टुरिझम प्रतिनिधी",
    en180: "ऑनलाईन सर्विस",
    en181: "मेणबत्ती बनवणे",
    en182: "लॉन्ड्री प्रशिक्षण",
    en183: "सौंदर्य सल्लागार प्रशिक्षण",
    en184: "औद्योगिक सुरक्षा रक्षक",
    en185: "बेकरी उत्पादने बनवणे",
    en186: "सॉफ्ट स्कील",
    en187: "सहाय्यक फायर ऑपरेटर",
    en188: "गुणवत्ता निरीक्षक",
    en189: "एअर कंडिशनिंग मेकॅनिक",
    en190: "कागदी पिशव्या/कागदी पाकिटे",
    en191: "मूलभूत संगणक शिक्षण",
    en192: "इंटरनेट प्रशिक्षण",
    en193: "मास्क बनवणे",
    en194: "प्रशिक्षण",
    en195: "सर्व प्रशिक्षण व त्यांच्या विषयी माहिती",
    en196: "अ.क्र",
    en197: "विषयाचे नाव",
    en198: "दिवस",
    en199: "तास",
    en199_: "शिकवणी",
    en200: "इंटेरियर डिझाईन व डेकोरेशन प्रशिक्षण.",
    en201: "४५ दिवस",
    en202: "९० तास",
    en203: "म्युरल पेंटिंग प्रशिक्षण.",
    en204: "१५ दिवस",
    en205: "३० तास",
    en206: "लमासा आर्ट प्रशिक्षण.",
    en207: "१५ दिवस",
    en208: "३० तास",
    en209: "ज्युट बॅग मेकिंग व बांबू आर्ट मेकिंग प्रशिक्षण.",
    en210: "३० दिवस",
    en211: "६० तास",
    en212: "फोटो लॅमिनेशन व फ्रेम प्रशिक्षण.",
    en213: "२० दिवस",
    en214: "४० तास",
    en215: "सॅनिटरी नॅपकिन प्रशिक्षण.",
    en216: "१० दिवस",
    en217: "२० तास",
    en218: "बाल संगोपन प्रशिक्षण.",
    en219: "१० दिवस",
    en220: "२० तास",
    en221: "विमा सल्लागार प्रशिक्षण.",
    en222: "३० दिवस ",
    en223: "६० तास",
    en224: "पोषक आहार व आरोग्य प्रशिक्षण.",
    en225: "३० दिवस",
    en226: "६० तास",
    en227: "फ्रंट ऑफिस कमिशन प्रशिक्षण.",
    en228: "४५ दिवस",
    en229: "९० तास",
    en230: "ट्रॅव्हल्स आणि टुरिझम प्रतिनिधी प्रशिक्षण.",
    en231: "६० दिवस",
    en232: "१२० तास",
    en233: "ऑनलाईन सर्विस प्रशिक्षण.",
    en234: "३० दिवस",
    en235: "६० तास",
    en236: "मेणबत्ती बनवणे कॅण्डल मेकिंग प्रशिक्षण.",
    en237: "१५ दिवस",
    en238: "३० तास",
    en239: "लॉन्ड्री प्रशिक्षण.",
    en240: "१५ दिवस",
    en241: "३० तास",
    en242: "सौंदर्य सल्लागार प्रशिक्षण.",
    en243: "६० दिवस",
    en244: "१२० तास",
    en245: "औद्योगिक सुरक्षा रक्षक प्रशिक्षण.",
    en246: "३० दिवस ",
    en247: "६० तास",
    en248: "बेकरी उत्पादने बनवणे प्रशिक्षण.",
    en249: "१५ दिवस",
    en250: "३० तास",
    en251: "सॉफ्ट स्कील फॉर बेसलाइन स्टाफ प्रशिक्षण.",
    en252: "३० दिवस ",
    en253: "६० तास",
    en254: "सहाय्यक फायर ऑपरेटर प्रशिक्षण.",
    en255: "३० दिवस",
    en256: "६० तास",
    en257: "गुणवत्ता निरीक्षक प्रशिक्षण.",
    en258: "३० दिवस ",
    en259: "६० तास",
    en260: "रेफ्रीजरेशन / एअर कंडिशनिंग मेकॅनिक प्रशिक्षण.",
    en261: "३० दिवस",
    en262: "६० तास",
    en263: "कागदी पिशव्या व कागदी पाकिटे तयार करणे प्रशिक्षण.",
    en264: "१० दिवस",
    en265: "२० तास",
    en266: "मूलभूत संगणक शिक्षणनाचे प्रशिक्षण.",
    en267: "३० दिवस ",
    en268: "६० तास",
    en269: "इंटरनेट प्रशिक्षण.",
    en270: "१५ दिवस",
    en271: "३० तास",
    en272: "कापडी पिशव्या व मास्क प्रशिक्षण.",
    en273: "१५ दिवस",
    en274: "३० तास",
    en275: "तंत्रज्ञान प्रशिक्षण आणि रोजगार संधी",
    en276:
      "शिक्षणाचे महत्त्व लक्षात घेता. नवीन पीढीच्या विकासासाठी आणि बेरोजगारीचा टक्का कमी करण्यासाठी DRDF ही नेहमी सक्रिय आणि प्रभावशाली पावले उचलत आली आहे. DRDF आणि धवलक्रांती यांच्या समन्वयाने काही ठोस आणि निर्णयात्मक-परिणात्मक पावले उचलण्यात आली. युवकांनी व युवतीने नवीन स्वयंरोजगार विकसित आणि निर्माण करावे. यासाठी त्यांना अभियांत्रिक तंत्रज्ञानाविषयी मार्गदर्शन, शिक्षण व प्रशिक्षण उपलब्ध करून. त्यांना रोजगाराची संधी उपलब्ध व्हावी. यासाठी सुद्धा विशेष प्रयत्न करण्यात आले. विद्यार्थ्यांचे प्रशिक्षण पूर्ण झाल्यावर त्यांना रोजगार मिळेपर्यंत चे मार्गदर्शन पुरवण्यासाठी सहकारी नेमण्यात आले. युवकांनी व युवतीने नवीन स्वयंरोजगार विकसित आणि निर्माण करावे. यासाठी त्यांना अभियांत्रिक तंत्रज्ञानाविषयी मार्गदर्शन, शिक्षण व प्रशिक्षण उपलब्ध करून. त्यांना रोजगाराची संधी उपलब्ध व्हावी.यासाठी सुद्धा विशेष प्रयत्न करण्यात आले. विद्यार्थ्यांचे प्रशिक्षण पूर्ण झाल्यावर त्यांना रोजगार मिळेपर्यंत चे मार्गदर्शन पुरवण्यासाठी सहकारी नेमण्यात आले.",
    en277:
      "इन्डो जर्मन टूल अंतर्गत १७८ विद्यार्थ्यांना वेगवेगळ्या तंत्रज्ञानाविषयी माहिती आणि मार्गदर्शन तसेच प्रशिक्षण देऊन. त्यांचा विकास घडवण्याचे काम सुरू आहे.",
    en278: "सिपेट (CIPET) च्या अंतर्गत ७८ विद्यार्थी प्रशिक्षण घेत आहेत.",
    en279: "तंत्रज्ञान प्रशिक्षण",
    en280: "इंन्डो जर्मन टूल्स प्रशिक्षण व त्यांच्या विषयी माहिती",
    en281: "मशीन ऑपरेशन्समधील प्रमाणपत्र अभ्यासक्रम",
    en282: "CNC ट्युरिंग आणि मिलिंग मध्ये प्रमाणपत्र अभ्यासक्रम",
    en283: "कंडेन्स्ड कोर्स इन टूल अँड डाय मेकिंग",
    en284: "CNC मिलिंग मध्ये प्रमाणपत्र अभ्यासक्रम",
    en285: "सीएनसी टर्निंगमध्ये प्रमाणपत्र अभ्यासक्रम",
    en286: "सीएनसी मशीनिंगमध्ये ॲडव्हान्स सर्टिफिकेट कोर्स",
    en287: "वेल्डिंग तंत्रज्ञानातील ॲडव्हान्स सर्टिफिकेट कोर्स",
    en288: "मशीनिंग मध्ये प्रमाणपत्र अभ्यासक्रम",
    en289: "पोस्ट-डिप्लोमा इन टूल अँड डाय मॅन्युफॅक्चरिंग",
    en290: "सीएनसी तंत्रज्ञानातील मास्टर सर्टिफिकेट कोर्स",
    en291: "मशीन ऑपरेटर - इंजेक्शन मोल्डिंग",
    en292: "सिपेट प्रशिक्षण व त्यांच्या विषयी माहिती",
    en293: "यंत्रसामग्रीची देखभाल - तंत्रज्ञ",
    en294: "यंत्रसामग्रीची देखभाल - तंत्रज्ञ",
    en295: "DRDF आणि कम्युनिटी पोलीस यांनी रोजगार उपलब्ध करून दिले.",
    en296:
      " एकोणविसी विद्यार्थ्यांना कंपनीमध्ये रोजगार देण्यात आला. त्यांना प्रतिदिन चारशे पन्नास अशी हजेरी देण्यात आली.",
    en297:
      " एकवीस विद्यार्थ्यांना सात हजार ते दहा हजार रुपये महिना पगार या रोजगार मोबदला वर ट्रेनि म्हणून कामाला लावले.",
    en298:
      "दहा विद्यार्थ्यांना प्रशिक्षण देऊन त्यांना ट्रेनि म्हणून रोबोटिक्स या क्षेत्रामध्ये काम मिळवून देण्यात आले.",
    en299:
      "चाळीस विद्यार्थ्यांना योग्य ते लेझर वेल्डिंग टेक्नॉलॉजी चे प्रशिक्षण देऊन त्यांना या तंत्रज्ञांना वरती काम मिळवून देण्यात आले.",
    en300: "दर्जेदार सोय आणि शैक्षणिक तयारीसाठी",
    en301:
      "विद्यार्थ्यांच्या ग्राउंड लेव्हल वरती समस्या समजून घेऊन त्यांना दर्जेदार शिक्षण घेता यावे आणि अभ्यासक्रमाची तयारी करता येईल. उत्तम आणि दर्जेदार शिक्षणाबरोबरच मुलांना अभ्यासाचे पर्यावरण निर्माण होणे अत्यंत गरजेचे आहे. त्यामुळे डी.आर.डी.एफ आणि धवलक्रांतीने ग्राउंड लेव्हल वर मुलांसाठी काही सोयी निर्माण करत. शैक्षणिक विकासाची जबाबदारी पार पडली.",
    en302:
      "ग्रंथालयाची विविध भागांमध्ये सोय : इंदिरानगर, शताब्दी नगर, बायजीपुरा, अनाथालय साठी ग्रंथालयाची सोय करण्यात आली.",
    en303:
      "स्टडी रूम ची सोय : राज्यसेवा आणि सिविल सर्विस ची तयारी करणाऱ्या मुलांसाठी आणि बायजीपुरा मधील अनाथ मुलांसाठी ग्रंथालयाची आणि स्टडी रूमची उभारणी.",
    en304:
      "विद्यार्थ्यांच्या आकलन क्षमतेसाठी विविध स्पर्धा : विविध शाळांमध्ये निबंध लेखनाच्या स्पर्धा परीक्षा घेण्यात आली.",
    en305:
      "नाईट क्लासेस ची सुरुवात केली : रात्रीच्या वेळेस प्रशिक्षण देण्याची सोय करण्यात आली.",
    en306:
      "विद्यार्थ्यांना त्यांच्या शैक्षणिक अभ्यासक्रमाची तयारी करता यावी यासाठी ग्रंथालय सोय करून देण्यात आली. विद्यार्थी राज्यसेवा व सिव्हिल सर्व्हिसेस अशा मोठमोठ्या अभ्यासक्रमाची तयारी करतात. त्यासाठी त्यांना अनुकूल ते वातावरण निर्माण होण्यासाठी ग्रंथालय आणि लायब्ररीची गरज असते.",
    en307: "इंदीरानगर, गारखेडा, औरंगाबाद मध्ये स्टडी सेंटरची सोय",
    en308:
      "बैतूल यतिम ट्रस्ट, किले आर्क, औरंगाबाद अनाथालयासाठी स्टडी सेंटरची सोय",
    en309: "शताब्दी नगर औरंगाबाद मध्ये स्टडी सेंटरची सोय",
    en310: "इंदिरानगर बायजिपुरा नूर गेट औरंगाबाद स्टडी सेंटरची सोय",
    en311:
      "संजय नगर,मुकुंदवाडी पोलीस स्टेशन शेजारी, औरंगाबाद मध्ये रात्रीचे प्रशिक्षण केंद्र सुरू करण्यात आले.साक्षरते मध्ये वाढ होण्यासाठी हा एक उपक्रम राबविण्यात आला . रात्रीच्या प्रशिक्षणासाठी सर्वांना प्रोत्साहन देण्यात आले आणि योग्य ते सर्व जबाबदारी पार पाडण्यात आली.",
    en312:
      "बायजीपुरा वॉर्ड मध्ये स्पर्धा परीक्षांची आणि पोलीस भरतीची तयारी करत असलेल्या विद्यार्थ्यांसाठी आणि संगणक विषयांमध्ये सुद्धा तयार करत असणाऱ्या विद्यार्थ्यांसाठी मोठ्या ग्रंथालयाची सोय करण्यात आली. तसेच त्या भागातील ग्रंथालयाचा २०० ते २५० अनाथ मुलांना ह्या ग्रंथालयाचा मोठा फायदा झाला.",
    en313:
      "अनेक मुलांना योग्य ते मार्गदर्शन न मिळाल्यामुळे ते कमी वयात चुकीच्या मार्गाला जातात. त्यामुळे त्यांना जर मार्गदर्शन केले तर ते एक उत्तम नागरिक बनण्याचे आणि समाजासाठी काहीतरी मोठे कार्य करण्याचे ध्येय स्वतःच्या मनामध्ये तयार करतात. त्यासाठी त्यांची मन परिवर्तन करण्याचे काम व त्यांना योग्य ते मार्गदर्शन देण्याचे काम धवलक्रांती ने विविध कार्यक्रमातून केले.",
    en314:
      "अनेक मुलांना योग्य ते मार्गदर्शन न मिळाल्यामुळे ते कमी वयात चुकीच्या मार्गाला जातात. त्यामुळे त्यांना जर मार्गदर्शन केले तर ते एक उत्तम नागरिक बनण्याचे आणि समाजासाठी काहीतरी मोठे कार्य करण्याचे ध्येय स्वतःच्या मनामध्ये तयार करतात. त्यासाठी त्यांची मन परिवर्तन करण्याचे काम व त्यांना योग्य ते मार्गदर्शन देण्याचे काम धवलक्रांती ने विविध कार्यक्रमातून केले.",
    en315:
      "कम्युनिटी पोलिसिंग डी.आर.डी.एफ ने कार्यक्रम आयोजन करून उद्योजकता वाढवण्यासाठी प्रोत्साहन दिले आणि मार्गदर्शन केले . शहरातील बेरोजगार युवकांसाठी कार्यशाळा राबवण्यात आली . ४८ तरुणांना प्रशिक्षण देण्यात आले आणि उद्योजकतेसाठी प्रोत्साहन दिले.",
    en316:
      "धवलक्रांती डी.आर.डी.एफ आणि कम्युनिटी पोलीसिंग समन्वय्याने महिलांसाठी उपक्रम राबवले.",
    en317:
      "महिलांना वेगवेगळ्या मार्गे स्वावलंबी आणि सक्षम बनवण्यासाठी धवलक्रांती नेहमीच अनेक प्रकारे प्रयत्न करत असते. जसे की महिलांना प्रशिक्षण देणे, त्यांना स्वरक्षणाची प्रशिक्षण देणे, अशिक्षित महिलांना साक्षरता प्रदान करणे, महिलांच्या आरोग्यासाठी वेगवेगळे उपक्रम राबवणे, महिलांना रोजगार देऊन त्यांना आत्मनिर्भर बनवणे. या विविध उपक्रमांसाठी धवलक्रांती नेहमीच डी.आर.डी.एफ आणि कम्यूनिटी पोलीसिंग सहकाऱ्यांच्या साह्याने निर्णयात्मक पावले आणि उपाय योजनांची अंमलबजावणी करते.",
    en318: "महिला सशक्तिकरण",
    en319: "लघु कौशल्यांसाठी प्रशिक्षण आणि बाजारपेठ उपलब्ध करून देणे.",
    en320: "१० महिलांना कॉटन विग बनवण्याचे प्रशिक्षण दिले.",
    en321: "सौंदर्य प्रसाधने प्रशिक्षण.",
    en322: "धूप बनवण्याचे प्रशिक्षण.",
    en323: "एलईडी लाईट्स मॅन्युफॅक्चरिंग.",
    en324: "कागदी पिशव्या बनवणे.",
    en325: "शिलाई मशीन वापरणे प्रशिक्षण.",
    en326:
      "शताब्दी नगर मध्ये १६ महिलांना शिलाई यंत्र मशीनचे प्रशिक्षण देण्यात आले.",
    en327:
      "क्रांती चौक येथील गरीब भागांमध्ये दीडशे महिलांना एलईडी बनवण्याची प्रशिक्षण देण्यात आले आणि त्यांना रोजगार उपलब्ध करून देण्यात आले.",
    en328:
      "प्लास्टिक बंदीमुळे रोजगार गेलेल्या महिलांना कागदी पिशवी कशा बनवायच्या याचे प्रशिक्षण देण्यात आले आणि त्याचबरोबर इंदिरानगर मधील सात महिला आणि मीसारवाडी मधील पंधरा महिला ना रोजगार उपलब्ध करून देण्यात आले.",
    en329:
      "बीप मांसा-वरती बंदी आल्यामुळे मुस्लिम महिला चे रोजगार गेले होते. अशा ४९ महिलांना कागदी पिशव्या बनवायची प्रशिक्षण देऊन. त्यांना रोजगार मिळवून देण्यात आला. मोती करंजा आणि सील्लेखान मधील महिलांचा ही समावेश होता.",
    en330:
      "ज्या महिलांना कागदी पिशवी बनवण्याचे प्रशिक्षण दिले होते त्यांनी अठरा दिवसांमध्ये ३४००० कागदी पिशवी तयार करून. त्यानी हॉस्पिटल्स, रेस्टॉरंट्स आणि मॉलमध्ये विकले.",
    en331:
      "हर्ष आणि संजय ब्युटी मॉल आणि डी.आर.डी.एफ बरोबर कम्युनिटी पोलीसिंग सहकार्याने काम करून ५० महिलांना आणि मुलींना सौंदर्यप्रसाधनाचे प्रशिक्षण दिले.",
    en332: "विविध उपक्रम आणि माहिती :",
    en333:
      "शताब्दी नगर,औरंगाबाद मध्ये १६ महीला ना धूप कसे बनवायचे याचे प्रशिक्षण देण्यात आले आणि नंतर त्यांना रोजगारही देण्यात आले.",
    en334:
      "क्रांती चौक,औरंगाबाद मधील गरीब भागांमध्ये एकूण १५० महिलांना एलईडी लाईट कशा बनवायच्या याचं प्रशिक्षण देऊन त्यांना रोजगार देण्यात आले.",
    en335:
      "वडगाव ( कोल्हाटी ) औरंगाबाद मधील २०० महिलांना शिलाई यंत्राचे प्रशिक्षण आणि शिलाई कामाचे प्रशिक्षण देऊन. त्यांना रोजगार ही देण्यात आले.",
    en336:
      "हर्ष आणि संजय ब्युटी मॉल तसेच डी.आर.डी.एफ यांच्यासोबत कम्युनिटी पोलीसिंग यांनी ५० महिलाना सौंदर्यप्रसाधनाचे प्रशिक्षण देऊन त्यांना स्वावलंबी बनवले.",
    en337:
      "महिला सशक्तीकरणासाठी आणि स्वरक्षणासाठी स्वतःचे रक्षण कसे करावे याची प्रशिक्षण विविध कॉलेज आणि भागांमध्ये १५५० युवतीना देण्यात आले.",
    en338:
      "अनेक महिलांनी विविध कारणांमुळे त्यांचे रोजगार गमवल्यामुळे त्यांना कागदी पिशव्या बनवायच्या कशा याच प्रशिक्षण देऊ त्यांना रोजगार उपलब्ध करून देण्यात आले.",
    en339:
      "प्लास्टिक बंद झाल्यामुळे अनेक महिलांनी त्यांची रोजगार गमावली.इंदिरानगर मधील सात महिलांना कागदी पिशव्या कशा बनवावे याचे प्रशिक्षण देऊन रोजगार देण्यात आले.",
    en340:
      "प्लास्टिक बंद झाल्यामुळे मिरसावाडी मधील महिलांनी त्यांची रोजगार गमावली.पंधरा महिलांना कागदी पिशव्या कशा बनवावे याची प्रशिक्षण देऊन रोजगार देण्यात आले.",
    en341:
      "बिफ बंद झाल्यामुळे मुस्लिम महिलांनी त्यांची रोजगार गमावली.मोती कारंजा,औरंगाबाद मधील काही महिलांना कागदी पिशव्या कशा बनवावे याची प्रशिक्षण देऊन रोजगार देण्यात आले.",
    en342:
      "बिफ बंद झाल्यामुळे सील्लेखाना,औरंगाबाद मधील काही महिलांना कागदी पिशव्या कशा बनवावे याची प्रशिक्षण देऊन रोजगार देण्यात आले.",
    en343:
      "महिलांनी घरगुती बनवलेल्या कापडी पिशव्यांना आणि इतर वस्तू विक्रीसाठी फ्रोजन मॉल,औरंगाबाद मध्ये दोन दिवसीय मार्केट उपलब्ध करून दिले.",
    en344:
      "वाळूज पोलीस स्टेशन एरिया, औरंगाबाद जवळील महिलांनी अठरा दिवसांमध्ये एकूण चौतीस हजार कागदी पिशव्या बनवून त्या हॉस्पिटल रेस्टॉरंट मॉल आणि इतर ठिकाणी विकल्या.",
    en345: "धवलक्रांती फाऊंडेशनच्या मार्फत कालबाह्य अन्न पुनर्वापरसाठी उपाय .",
    en346:
      "मोठ्या प्रमाणात निर्माण होणारे कालबाह्य अन्न जे मानसोपयोगी नसले तरी त्याचा पुनर्वापर करून आपण त्यापासून खत निर्मिती करू शकतो जे आपण आपल्या शेतीचा कस वाढवण्यासाठी तसेच आपण त्या कालबाह्य अन्नापासून विविध प्रकारचे घरगुती गाई म्हशी यांच्यासाठी सुद्धा पशुखाद्याची निर्मिती करू शकतो याचाच विचार करून धवलक्रांती फाउंडेशन ही विविध अशा कालबाह्य अन्न निर्माण करणाऱ्या जागा आणि कंपनी यांच्याशी संपर्क साधून त्यांच्याकडून सर्व कालबाह्य अन्न एकत्रित करून त्याच्यावरती प्रोसेस करून त्याचा खत निर्मितीसाठी व प्राण्यांसाठी अन्न निर्मिती करण्याचा विचार हा धवल क्रांतीच्या मनात आला.",
    en347: "कालबाह्य पदार्थापासून खत आणि पशुखाद्याची निर्मिती :",
    en348:
      "कालबाह्य झालेले खाण्याचे पदार्थ संकलन करून त्यापासून नैसर्गिक खताची निर्मिती करणे",
    en349:
      "शेत जमिनीचा पोत सुधारण्यासाठी विविध उपक्रम राबवून त्या अनुषंगाने कार्य करणे",
    en350:
      "महिला स्वयंसहाय्यता गटामार्फत दुग्ध व्यवसायाच्या अनुषंगाने पूरक कुटीर/लघुउद्योग व्यवसाय संबंधी क्षमता बांधणी प्रशिक्षण व कृती कार्यक्रम हाती घेणे",
    en351:
      "कृषी महाविद्यालय, कृषी विश्वविद्यालयामार्फत नाविन्यपूर्ण व ग्रामीण भागातील शेतकऱ्यांची शेती व शेतीपूरक व्यवसाय विकास संबंधित चर्चासत्र आयोजन करणे गरजेनुसार योग्य असे संशोधन कार्य हाती घेणे.",
    en352:
      "पशुखाद्यांची नैसर्गिक प्रक्रियेतुन निर्मिती करून मुक्या जनावरांसाठी च्या कल्याणासाठी शेतकऱ्यांच्या हितासाठी शासनाच्या व संस्थेच्या विविध योजनांची अंमलबजावणी करून त्या जागोजागी कार्य करणे",
    en353: "महत्वाचे पाने",
    en354: "मुख्यपुष्ट",
    en355: "माहिती",
    en356: "कामे",
    en356_1: "महिला सशक्तिकरण",
    en356_2: "प्रशिक्षण",
    en356_3: "उत्पादने",
    en357: "फोटो",
    en358: "अधिक माहितीसाठी",
    en359: "फ्लॅट न. १०८, गेट न.२२८/१, अमृत औरा",
    en359_1: " देहू-आळंदी रोड, मोशी",
    en359_2: "महाराष्ट्र - ४१२ १०५",
    en360: "संपर्क : (+९१) ८४२१५९६९१२",
    en361: "डॉ. किशोर उडान : +(९१) ९४२१४२१४४०",
    en362: "प्रवीण जाधव : +(९१) ७३५००००३६९",
    en363: "२४ / ७ आपल्या सेवेत",
    en364: "पत्ता",
    en10d: "१० दिवस",
    en15d: "१५ दिवस",
    en20d: "२० दिवस",
    en30d: "३० दिवस",
    en45d: "४५ दिवस",
    en60d: "६० दिवस",
    en90d: "९० दिवस",
    en01: "१",
    en02: "२",
    en03: "३",
    en04: "४",
    en05: "५",
    en06: "६",
    en07: "७",
    en08: "८",
    en09: "९",
    en010: "१०",
    en011: "११",
    en012: "१२",
    en013: "१३",
    en014: "१४",
    en015: "१५",
    en016: "१६",
    en017: "१७",
    en018: "१८",
    en019: "१९",
    en020: "२०",
    en021: "२१",
    en022: "२२",
    en023: "२३",
    en024: "२४",
    en025: "२५",
    eng1:"सर्व फोटो",
eng2:"करोना",
eng3:"समाजकार्य",
eng4:"कॉम्युनिटी पोलीसिंग",
eng5:"इतर ",
  },
};

